theme = "default"
client_id = "65b708073fc0480ea92a077233ca87bd"
playack_format = "{track} • {artists}\n{album}\n{metadata}"
notify_format = { summary = "{track} • {artists}", body = "{album}" }
# the default `copy_command` is based on the OS
copy_command = { command = "pbcopy", args = [] } # macos
# copy_command = { command = "xclip", args = ["-sel", "c"] } # linux
# copy_command = { command = "clip", args = [] } # windows
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
cover_image_refresh_duration_in_ms = 2000
page_size_in_rows = 20
track_table_item_max_len = 32
enable_media_control = false
enable_streaming = true
default_device = "spotify-player"
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
playback_window_position = "Top"
cover_img_length = 9
cover_img_width = 5
playback_window_width = 6

[device]
name = "spotify-player"
device_type = "speaker"
volume = 50
bitrate = 160
audio_cache = false
